complete task 3.1
js-tasks-ru/vue-20220616_devel-js pull request #4
Opened 2022-07-09 07:48 UTC by DeveL-oz

2022-07-09 07:54 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-07-09 10:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-10 07:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-10 15:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-11 14:39 UTC, ShGKme requested changes
В `UiToast` требуется перенести ту часть вёрстки и стилей, которые явно относятся к тосту. Иначе `UiToast` нельзя использовать, как полноценный компонент, так он не имеет смысла.

Остальные задачи приняты.

2022-07-11 14:39 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToasts.vue
> +  </div>
> нужно ли использовать v-if в подобных случаях? или необязательно, также и в UiToast на span у меня v-if стоит

`v-if` на корневом элементе, который зависит от данных родителя, не нужен практически никогда. Если вывод компонента списка тостов не нужен, когда тостов нет, то родительский компонент может не выводить `UiToaster`. Но такое актуально обычно только, если этот пустой див без тостов как-то мешает вёрсткой

2022-07-11 14:39 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToasts.vue
> +    </div>
`<div class="toast"` - явно часть компонента тоста. Без него компонент `UiToast` нельзя использовать, стили тоста также привязаны к этому диву.

2022-07-13 19:29 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-07-14 12:22 UTC, ShGKme approved these changes
Принято 👍

2022-07-14 12:22 UTC, merged